---
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: '2.7'

Lint/RescueException:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 15

Metrics/ClassLength:
  Enabled: false

Naming/MethodParameterName:
  Exclude:
    - 'lib/smart_proxy_salt/salt.rb'

Style/HashSyntax:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/OptionalBooleanParameter:
  Exclude:
    - 'lib/smart_proxy_salt/cli.rb'
